version: '3'

services:

  app:
    container_name: app-$PROJECT
    # build: .
    image: vupar/app:8.1
    restart: unless-stopped
    env_file: .env
    networks:
      - dev
    volumes:
      - .:/var/www/dev/$PROJECT
      - ~/.ssh:/home/www-data/.ssh
    working_dir: /var/www/dev/$PROJECT
    hostname: $PROJECT.dev.local
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - traefik.http.routers.$PROJECT-app.entrypoints=https
      - traefik.http.routers.$PROJECT-app.rule=Host(`$PROJECT.dev.local`)
      - traefik.http.routers.$PROJECT-app.tls=true

networks:
  dev:
    external: true
